apiVersion: v1
kind: Secret
metadata:
  name: staging-db-credentials
  namespace: staging
type: Opaque
data:
  # Base64 encoded RDS username
  username: c3_ST_RhZ2luZ3VzZXI=  # Replace with actual username (Base64 encoded)
  # Base64 encoded RDS password
  password: c3R_ST_hZ2luZHBhc3M=  # Replace with actual password (Base64 encoded)

