apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: staging
  name: developer
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments"]
  verbs: ["create", "list", "get", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "list", "get", "update"]

